# Generated by Django 2.2.5 on 2021-06-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_bookedday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled')], default='pending', max_length=12),
        ),
    ]
